import 'reflect-metadata';
import { DataSource } from 'typeorm';
import { envs } from '@/config/env';
import {
  AcuteTreatmentWorseFeedbackOptionsEntity,
  AppVersionEntity,
  DeviceEntity,
  FeelingTodayEntity,
  MigraineLogEntity,
  NewQuestionEntity,
  NewSelectionEntity,
  NewTranslationEntity,
  NewUserResponseEntity,
  PreferredAnswersEntity,
  PreventiveTreatmentEntity,
  PreventiveTreatmentScheduleEntity,
  PreventiveTreatmentScheduleMetadataEntity,
  ProfileEntity,
  PushNotificationTokenEntity,
  QuestionEntity,
  SelectionEntity,
  SessionEntity,
  TranslationEntity,
  UserEntity,
  UserResponseEntity,
  UserResponseAcuteTreatmentWorseFeedbackOptionsEntity,
} from '@/infra/database/entities';

export const dataSource = new DataSource({
  type: 'postgres',
  host: envs.DB_HOST,
  port: envs.DB_PORT,
  username: envs.DB_USER,
  password: envs.DB_PASSWORD,
  database: envs.DB_NAME,
  uuidExtension: 'pgcrypto',
  entities: [
    AcuteTreatmentWorseFeedbackOptionsEntity,
    AppVersionEntity,
    DeviceEntity,
    FeelingTodayEntity,
    MigraineLogEntity,
    NewQuestionEntity,
    NewSelectionEntity,
    NewTranslationEntity,
    NewUserResponseEntity,
    PreferredAnswersEntity,
    PreventiveTreatmentEntity,
    PreventiveTreatmentScheduleEntity,
    PreventiveTreatmentScheduleMetadataEntity,
    ProfileEntity,
    PushNotificationTokenEntity,
    QuestionEntity,
    SelectionEntity,
    SessionEntity,
    TranslationEntity,
    UserEntity,
    UserResponseEntity,
    UserResponseAcuteTreatmentWorseFeedbackOptionsEntity,
  ],
  migrations: ['src/infra/database/migrations/**/*.ts'],
  synchronize: false,
});
